version: '3.10'
services:
  backend:
    build:
      context: .
    container_name: BIF
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - dockernet

  postgres-db:
    image: 'postgres:15'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dockernet

volumes:
  postgres-data:

networks:
  dockernet:
    external: true
    driver: bridge
