# Generated by Django 4.2.3 on 2024-08-06 10:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок текста')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок текста')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок текста')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок текста')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание текста')),
                ('descriptions_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание текста')),
                ('descriptions_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание текста')),
                ('descriptions_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание текста')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Детальное описание о проекте на странице - О проекте',
            },
        ),
        migrations.CreateModel(
            name='AboutBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок баннера страницы - О проекте')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - О проекте')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - О проекте')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - О проекте')),
                ('descriptions', models.TextField(verbose_name='Описание баннера страницы - О проекте')),
                ('descriptions_ru', models.TextField(null=True, verbose_name='Описание баннера страницы - О проекте')),
                ('descriptions_ky', models.TextField(null=True, verbose_name='Описание баннера страницы - О проекте')),
                ('descriptions_en', models.TextField(null=True, verbose_name='Описание баннера страницы - О проекте')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Фото баннера страницы - О проекте')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки баннера страницы - О проекте',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото (нужно добавить фото)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Галерея на странице - О проекте',
            },
        ),
        migrations.CreateModel(
            name='GalleryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовк (заголовок для раздела фотографии)')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовк (заголовок для раздела фотографии)')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовк (заголовок для раздела фотографии)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовк (заголовок для раздела фотографии)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Фотографи на странице - О проекте',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок раздела Истории')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок раздела Истории')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок раздела Истории')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок раздела Истории')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание раздела Истории')),
                ('descriptions_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание раздела Истории')),
                ('descriptions_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание раздела Истории')),
                ('descriptions_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание раздела Истории')),
                ('year_1', models.CharField(max_length=255, verbose_name='Указать 1 год')),
                ('year_2', models.CharField(max_length=255, verbose_name='Указать 2 год')),
                ('year_3', models.CharField(max_length=255, verbose_name='Указать 3 год')),
                ('year_4', models.CharField(max_length=255, verbose_name='Указать 4 год')),
                ('year_5', models.CharField(max_length=255, verbose_name='Указать 5 год')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Перечисление годов на странице - О проекте',
            },
        ),
        migrations.CreateModel(
            name='HistoryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок (указать год и заголовок)')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок (указать год и заголовок)')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок (указать год и заголовок)')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок (указать год и заголовок)')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание (написать описание для этого года)')),
                ('descriptions_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание (написать описание для этого года)')),
                ('descriptions_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание (написать описание для этого года)')),
                ('descriptions_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание (написать описание для этого года)')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (youtube)')),
                ('url_ru', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (youtube)')),
                ('url_ky', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (youtube)')),
                ('url_en', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео (youtube)')),
                ('amount_invest', models.CharField(max_length=255, verbose_name='Объем привлеченных инвестиций (указать цену в $)')),
                ('amount_invest_ru', models.CharField(max_length=255, null=True, verbose_name='Объем привлеченных инвестиций (указать цену в $)')),
                ('amount_invest_ky', models.CharField(max_length=255, null=True, verbose_name='Объем привлеченных инвестиций (указать цену в $)')),
                ('amount_invest_en', models.CharField(max_length=255, null=True, verbose_name='Объем привлеченных инвестиций (указать цену в $)')),
                ('amount_projet', models.CharField(max_length=255, verbose_name='Количество заявленных проекто (указать количество)')),
                ('amount_projet_ru', models.CharField(max_length=255, null=True, verbose_name='Количество заявленных проекто (указать количество)')),
                ('amount_projet_ky', models.CharField(max_length=255, null=True, verbose_name='Количество заявленных проекто (указать количество)')),
                ('amount_projet_en', models.CharField(max_length=255, null=True, verbose_name='Количество заявленных проекто (указать количество)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Детальное описание каждого года на странице - О проекте',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Сумма (количество)')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Сумма (количество)')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Сумма (количество)')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Сумма (количество)')),
                ('descriptions', models.TextField(verbose_name='Описание - суммы (количество)')),
                ('descriptions_ru', models.TextField(null=True, verbose_name='Описание - суммы (количество)')),
                ('descriptions_ky', models.TextField(null=True, verbose_name='Описание - суммы (количество)')),
                ('descriptions_en', models.TextField(null=True, verbose_name='Описание - суммы (количество)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки статистики на странице - О проекте',
            },
        ),
    ]
