# Generated by Django 4.2.3 on 2024-08-06 10:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок баннера страницы - Выставка')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - Выставка')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - Выставка')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - Выставка')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание баннера страницы - Выставка')),
                ('descriptions_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание баннера страницы - Выставка')),
                ('descriptions_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание баннера страницы - Выставка')),
                ('descriptions_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание баннера страницы - Выставка')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки баннера страницы - Выставка',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_exhibition', verbose_name='Фото (первое фото, будет сверху)')),
                ('image_ru', models.ImageField(null=True, upload_to='slider_exhibition', verbose_name='Фото (первое фото, будет сверху)')),
                ('image_ky', models.ImageField(null=True, upload_to='slider_exhibition', verbose_name='Фото (первое фото, будет сверху)')),
                ('image_en', models.ImageField(null=True, upload_to='slider_exhibition', verbose_name='Фото (первое фото, будет сверху)')),
                ('image_2', models.ImageField(upload_to='slider_exhibition', verbose_name='Фото (второе фото, будет снизу)')),
                ('image_2_ru', models.ImageField(null=True, upload_to='slider_exhibition', verbose_name='Фото (второе фото, будет снизу)')),
                ('image_2_ky', models.ImageField(null=True, upload_to='slider_exhibition', verbose_name='Фото (второе фото, будет снизу)')),
                ('image_2_en', models.ImageField(null=True, upload_to='slider_exhibition', verbose_name='Фото (второе фото, будет снизу)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки слайдера на странице - Выставка',
            },
        ),
    ]
