# Generated by Django 4.2.3 on 2024-08-17 06:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentStand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_ru', models.URLField(verbose_name='Арендовать стенд (ссылка на рус.)')),
                ('url_ky', models.URLField(verbose_name='Арендовать стенд (ссылка на кырг.)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Арендовать стенд',
            },
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='descriptions',
            field=ckeditor.fields.RichTextField(verbose_name='Описание страницы - Выставка'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='descriptions_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание страницы - Выставка'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='descriptions_ky',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание страницы - Выставка'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='descriptions_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Описание страницы - Выставка'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок страницы - Выставка'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы - Выставка'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы - Выставка'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок страницы - Выставка'),
        ),
    ]
