# Generated by Django 4.2.3 on 2024-08-06 10:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_the_forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок для раздела о форуме')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок для раздела о форуме')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок для раздела о форуме')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок для раздела о форуме')),
                ('descriptions', models.CharField(max_length=155, verbose_name='Описание для раздела о форуме')),
                ('descriptions_ru', models.CharField(max_length=155, null=True, verbose_name='Описание для раздела о форуме')),
                ('descriptions_ky', models.CharField(max_length=155, null=True, verbose_name='Описание для раздела о форуме')),
                ('descriptions_en', models.CharField(max_length=155, null=True, verbose_name='Описание для раздела о форуме')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Раздел о форуме на главной странице',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок для баннера на главной странице')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок для баннера на главной странице')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок для баннера на главной странице')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок для баннера на главной странице')),
                ('descriptions', models.TextField(verbose_name='Описание для баннера на главной странице')),
                ('descriptions_ru', models.TextField(null=True, verbose_name='Описание для баннера на главной странице')),
                ('descriptions_ky', models.TextField(null=True, verbose_name='Описание для баннера на главной странице')),
                ('descriptions_en', models.TextField(null=True, verbose_name='Описание для баннера на главной странице')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Фото для баннера на главной странице')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки баннера на главной странице',
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип BIF')),
                ('logo_2', models.ImageField(upload_to='logo/', verbose_name='Логотип GREEN ECONOMY')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Логотипы BIF и GREEN ECONOMY на сайте',
            },
        ),
        migrations.CreateModel(
            name='SliderTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('title_ru', models.TextField(null=True, verbose_name='Заголовок')),
                ('title_ky', models.TextField(null=True, verbose_name='Заголовок')),
                ('title_en', models.TextField(null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки раздела - Участники выставки',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок для видео на главной странице')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок для видео на главной странице')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок для видео на главной странице')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок для видео на главной странице')),
                ('descriptions', ckeditor.fields.RichTextField(verbose_name='Описание для видео на главной странице')),
                ('descriptions_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание для видео на главной странице')),
                ('descriptions_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание для видео на главной странице')),
                ('descriptions_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание для видео на главной странице')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('url_ru', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('url_ky', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('url_en', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки видео на главной странице',
            },
        ),
        migrations.CreateModel(
            name='What_will_title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок для раздела - Что вас будет ждать на главном бизнес событии года')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок для раздела - Что вас будет ждать на главном бизнес событии года')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок для раздела - Что вас будет ждать на главном бизнес событии года')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок для раздела - Что вас будет ждать на главном бизнес событии года')),
                ('descriptions', models.CharField(max_length=155, verbose_name='Описание для раздела - Что вас будет ждать на главном бизнес событии года')),
                ('descriptions_ru', models.CharField(max_length=155, null=True, verbose_name='Описание для раздела - Что вас будет ждать на главном бизнес событии года')),
                ('descriptions_ky', models.CharField(max_length=155, null=True, verbose_name='Описание для раздела - Что вас будет ждать на главном бизнес событии года')),
                ('descriptions_en', models.CharField(max_length=155, null=True, verbose_name='Описание для раздела - Что вас будет ждать на главном бизнес событии года')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки раздела - Что вас будет ждать на главном бизнес событии года?',
            },
        ),
        migrations.CreateModel(
            name='WhatWill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Описание')),
                ('title_ru', models.CharField(max_length=155, null=True, verbose_name='Описание')),
                ('title_ky', models.CharField(max_length=155, null=True, verbose_name='Описание')),
                ('title_en', models.CharField(max_length=155, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
                ('what_will_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatwills', to='base.what_will_title', verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Элементы раздела - Что вас будет ждать на главном бизнес событии года?',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
                ('slidertitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliders', to='base.slidertitle', verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Раздел участники выставки на главной странице',
            },
        ),
    ]
