# Generated by Django 4.2.3 on 2024-08-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderTitleSponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('title_ru', models.TextField(null=True, verbose_name='Заголовок')),
                ('title_ky', models.TextField(null=True, verbose_name='Заголовок')),
                ('title_en', models.TextField(null=True, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Спонсоры и партнеры - Участники выставки',
            },
        ),
        migrations.CreateModel(
            name='SliderSponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
                ('slidertitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sliderssponsor', to='base.slidertitlesponsors', verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Спонсоры и партнеры на главной странице',
            },
        ),
    ]
