# Generated by Django 4.2.3 on 2024-08-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_slidertitlesponsors_slidersponsors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Кнопка (Подать проект на BIF 2024)')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Кнопка (Подать проект на BIF 2024)')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Кнопка (Подать проект на BIF 2024)')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Кнопка (Подать проект на BIF 2024)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Подать проект на BIF 2024',
            },
        ),
    ]
