# Generated by Django 4.2.3 on 2024-08-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_button'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип BIF'),
        ),
        migrations.AlterField(
            model_name='base',
            name='logo_2',
            field=models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип GREEN ECONOMY'),
        ),
    ]
