# Generated by Django 4.2.3 on 2024-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_base_logo_alter_base_logo_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidersponsors',
            name='title',
            field=models.TextField(default=1, verbose_name='Названия партнера'),
            preserve_default=False,
        ),
    ]
