# Generated by Django 4.2.3 on 2024-08-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_slidersponsors_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slidersponsors',
            old_name='title',
            new_name='title_sponsers',
        ),
    ]
