# Generated by Django 4.2.3 on 2024-08-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_title_slidersponsors_title_sponsers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidersponsors',
            name='title_sponsers',
            field=models.CharField(max_length=255, verbose_name='Названия партнера'),
        ),
    ]
