# Generated by Django 4.2.3 on 2024-08-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_slidersponsors_title_sponsers'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidersponsors',
            name='title_sponsers_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия партнера'),
        ),
        migrations.AddField(
            model_name='slidersponsors',
            name='title_sponsers_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия партнера'),
        ),
        migrations.AddField(
            model_name='slidersponsors',
            name='title_sponsers_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Названия партнера'),
        ),
    ]
