# Generated by Django 4.2.3 on 2024-08-06 10:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок баннера страницы - Бизнес проекты')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - Бизнес проекты')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - Бизнес проекты')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - Бизнес проекты')),
                ('descriptons', ckeditor.fields.RichTextField(verbose_name='Описание баннера страницы - Бизнес проекты')),
                ('descriptons_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание баннера страницы - Бизнес проекты')),
                ('descriptons_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание баннера страницы - Бизнес проекты')),
                ('descriptons_en', ckeditor.fields.RichTextField(null=True, verbose_name='Описание баннера страницы - Бизнес проекты')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки баннера страницы - Бизнес проекты',
            },
        ),
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (Нужно написать описание для фото)')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (Нужно написать описание для фото)')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (Нужно написать описание для фото)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (Нужно написать описание для фото)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='фото (Нужно указать изображение)')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='фото (Нужно указать изображение)')),
                ('image_ky', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='фото (Нужно указать изображение)')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='фото (Нужно указать изображение)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Перечень необходимого - Бизнес проекты',
            },
        ),
        migrations.CreateModel(
            name='YearlyCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год - (Указать год)')),
                ('image', models.ImageField(upload_to='catalog_images/', verbose_name='Изображение - (фото каталога)')),
                ('image_ru', models.ImageField(null=True, upload_to='catalog_images/', verbose_name='Изображение - (фото каталога)')),
                ('image_ky', models.ImageField(null=True, upload_to='catalog_images/', verbose_name='Изображение - (фото каталога)')),
                ('image_en', models.ImageField(null=True, upload_to='catalog_images/', verbose_name='Изображение - (фото каталога)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Годовые каталоги страницы - Бизнес проекты',
            },
        ),
        migrations.CreateModel(
            name='BusinessProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (Для раздела - Участие открыто для всех предпринимателей с действующим бизнесом!)')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (Для раздела - Участие открыто для всех предпринимателей с действующим бизнесом!)')),
                ('title_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (Для раздела - Участие открыто для всех предпринимателей с действующим бизнесом!)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок (Для раздела - Участие открыто для всех предпринимателей с действующим бизнесом!)')),
                ('descriptons', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (Участие открыто для всех предпринимателей с действующим бизнесом!)')),
                ('descriptons_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (Участие открыто для всех предпринимателей с действующим бизнесом!)')),
                ('descriptons_ky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (Участие открыто для всех предпринимателей с действующим бизнесом!)')),
                ('descriptons_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание (Участие открыто для всех предпринимателей с действующим бизнесом!)')),
                ('scroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.scroll', verbose_name='Перечень необходимого')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Участие открыто для всех предпринимателей с действующим бизнесом! на странице - Бизнес проекты',
            },
        ),
    ]
