# Generated by Django 4.2.3 on 2024-08-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_options_alter_yearlycatalog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yearlycatalog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='catalog_pdf/', verbose_name='Изображение - (фото каталога)'),
        ),
        migrations.AlterField(
            model_name='yearlycatalog',
            name='image_en',
            field=models.FileField(blank=True, null=True, upload_to='catalog_pdf/', verbose_name='Изображение - (фото каталога)'),
        ),
        migrations.AlterField(
            model_name='yearlycatalog',
            name='image_ky',
            field=models.FileField(blank=True, null=True, upload_to='catalog_pdf/', verbose_name='Изображение - (фото каталога)'),
        ),
        migrations.AlterField(
            model_name='yearlycatalog',
            name='image_ru',
            field=models.FileField(blank=True, null=True, upload_to='catalog_pdf/', verbose_name='Изображение - (фото каталога)'),
        ),
    ]
