# Generated by Django 4.2.3 on 2024-08-19 11:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок банера (на странице Регистрация на форум)')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок банера (на странице Регистрация на форум)')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок банера (на странице Регистрация на форум)')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок банера (на странице Регистрация на форум)')),
                ('descriptons', models.TextField(verbose_name='Описание банера (на странице Регистрация на форум)')),
                ('descriptons_ru', models.TextField(null=True, verbose_name='Описание банера (на странице Регистрация на форум)')),
                ('descriptons_ky', models.TextField(null=True, verbose_name='Описание банера (на странице Регистрация на форум)')),
                ('descriptons_en', models.TextField(null=True, verbose_name='Описание банера (на странице Регистрация на форум)')),
            ],
            options={
                'verbose_name': 'Настройки банера страницы -  Регистрация на форум',
            },
        ),
        migrations.CreateModel(
            name='SectorStandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Выбрать (добавить новый сектор)')),
            ],
            options={
                'verbose_name': 'Добавление секторов для Стандартного пакета на странице - Регистрация на форум',
                'verbose_name_plural': 'Секторы',
            },
        ),
        migrations.CreateModel(
            name='SectorVip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Выбрать (добавить новый сектор)')),
            ],
            options={
                'verbose_name': 'Добавление секторов для VIP пакета на странице - Регистрация на форум',
                'verbose_name_plural': 'Секторы',
            },
        ),
        migrations.CreateModel(
            name='Standart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Заголовок билета 'Стандарт'")),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name="Заголовок билета 'Стандарт'")),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name="Заголовок билета 'Стандарт'")),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name="Заголовок билета 'Стандарт'")),
                ('descriptons', ckeditor.fields.RichTextField(verbose_name="Описание билета 'Стандарт'")),
                ('descriptons_ru', ckeditor.fields.RichTextField(null=True, verbose_name="Описание билета 'Стандарт'")),
                ('descriptons_ky', ckeditor.fields.RichTextField(null=True, verbose_name="Описание билета 'Стандарт'")),
                ('descriptons_en', ckeditor.fields.RichTextField(null=True, verbose_name="Описание билета 'Стандарт'")),
            ],
            options={
                'verbose_name': 'Настройки билета Стандарт на странице -  Регистрация на форум',
            },
        ),
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Заголовок билета 'VIP'")),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name="Заголовок билета 'VIP'")),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name="Заголовок билета 'VIP'")),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name="Заголовок билета 'VIP'")),
                ('descriptons', ckeditor.fields.RichTextField(verbose_name="Описание билета 'VIP'")),
                ('descriptons_ru', ckeditor.fields.RichTextField(null=True, verbose_name="Описание билета 'VIP'")),
                ('descriptons_ky', ckeditor.fields.RichTextField(null=True, verbose_name="Описание билета 'VIP'")),
                ('descriptons_en', ckeditor.fields.RichTextField(null=True, verbose_name="Описание билета 'VIP'")),
            ],
            options={
                'verbose_name': 'Настройки билета VIP на странице -  Регистрация на форум',
            },
        ),
        migrations.CreateModel(
            name='ReachVip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('name_company', models.CharField(max_length=255, verbose_name='Название вашей компании')),
                ('current', models.CharField(max_length=255, verbose_name='Количество билетов')),
                ('email', models.CharField(max_length=255, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.sectorvip', verbose_name='Укажите сектор (Нужно создать или добавить)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Форма бронирования для VIP пакета - Регистрация на форум',
            },
        ),
        migrations.CreateModel(
            name='ReachStandart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('name_company', models.CharField(max_length=255, verbose_name='Название вашей компании')),
                ('current', models.CharField(max_length=255, verbose_name='Количество билетов')),
                ('email', models.CharField(max_length=255, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефона')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.sectorstandart', verbose_name='Укажите сектор (Нужно создать или добавить)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Форма бронирования для Стандартного пакета - Регистрация на форум',
            },
        ),
    ]
