# Generated by Django 4.2.3 on 2024-08-19 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': '', 'verbose_name_plural': 'Настройки банера страницы -  Регистрация на форум'},
        ),
        migrations.AlterModelOptions(
            name='sectorstandart',
            options={'verbose_name': '', 'verbose_name_plural': 'Добавление секторов для Стандартного пакета на странице - Регистрация на форум'},
        ),
        migrations.AlterModelOptions(
            name='sectorvip',
            options={'verbose_name': '', 'verbose_name_plural': 'Добавление секторов для VIP пакета на странице - Регистрация на форум'},
        ),
        migrations.AlterModelOptions(
            name='standart',
            options={'verbose_name': '', 'verbose_name_plural': 'Настройки билета Стандарт на странице -  Регистрация на форум'},
        ),
        migrations.AlterModelOptions(
            name='vip',
            options={'verbose_name': '', 'verbose_name_plural': 'Настройки билета VIP на странице -  Регистрация на форум'},
        ),
    ]
