# Generated by Django 4.2.3 on 2024-08-20 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='descriptons',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='descriptons_en',
            new_name='descriptions_en',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='descriptons_ky',
            new_name='descriptions_ky',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='descriptons_ru',
            new_name='descriptions_ru',
        ),
        migrations.RenameField(
            model_name='standart',
            old_name='descriptons',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='standart',
            old_name='descriptons_en',
            new_name='descriptions_en',
        ),
        migrations.RenameField(
            model_name='standart',
            old_name='descriptons_ky',
            new_name='descriptions_ky',
        ),
        migrations.RenameField(
            model_name='standart',
            old_name='descriptons_ru',
            new_name='descriptions_ru',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='descriptons',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='descriptons_en',
            new_name='descriptions_en',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='descriptons_ky',
            new_name='descriptions_ky',
        ),
        migrations.RenameField(
            model_name='vip',
            old_name='descriptons_ru',
            new_name='descriptions_ru',
        ),
    ]
