# Generated by Django 4.2.3 on 2024-08-06 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок баннера страницы - Источники финансирования')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - Источники финансирования')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - Источники финансирования')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок баннера страницы - Источники финансирования')),
                ('image', models.ImageField(max_length=255, upload_to='image/', verbose_name='Фото баннера страницы - Источники финансирования')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки баннера страницы - Источники финансирования',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройки фото - Источники финансирования',
            },
        ),
        migrations.CreateModel(
            name='ImageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Фото')),
                ('image_ru', models.ImageField(null=True, upload_to='image/', verbose_name='Фото')),
                ('image_ky', models.ImageField(null=True, upload_to='image/', verbose_name='Фото')),
                ('image_en', models.ImageField(null=True, upload_to='image/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Информация фото на странице - Источники финансирования',
            },
        ),
        migrations.CreateModel(
            name='LegalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Выбрать (добавить юридическое название)')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Выбрать (добавить юридическое название)')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Выбрать (добавить юридическое название)')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Выбрать (добавить юридическое название)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Добавление юридических названий на странице - Источники финансирования',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Выбрать (добавить новый сектор)')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Выбрать (добавить новый сектор)')),
                ('name_ky', models.CharField(max_length=255, null=True, verbose_name='Выбрать (добавить новый сектор)')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Выбрать (добавить новый сектор)')),
            ],
            options={
                'verbose_name': 'Добавление секторов на странице - Источники финансирования',
                'verbose_name_plural': 'Секторы',
            },
        ),
        migrations.CreateModel(
            name='Reach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('full_name_ru', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('full_name_ky', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('full_name_en', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('name_company', models.CharField(max_length=255, verbose_name='Название вашей компании')),
                ('name_company_ru', models.CharField(max_length=255, null=True, verbose_name='Название вашей компании')),
                ('name_company_ky', models.CharField(max_length=255, null=True, verbose_name='Название вашей компании')),
                ('name_company_en', models.CharField(max_length=255, null=True, verbose_name='Название вашей компании')),
                ('brief_description', models.CharField(max_length=255, verbose_name='Краткое описание деятельности вашей компании')),
                ('brief_description_ru', models.CharField(max_length=255, null=True, verbose_name='Краткое описание деятельности вашей компании')),
                ('brief_description_ky', models.CharField(max_length=255, null=True, verbose_name='Краткое описание деятельности вашей компании')),
                ('brief_description_en', models.CharField(max_length=255, null=True, verbose_name='Краткое описание деятельности вашей компании')),
                ('legal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financing.legalname', verbose_name='Юридическое название (Нужно создать или добавить)')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financing.sector', verbose_name='Укажите сектор (Нужно создать или добавить)')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Форма связи на странице - Источники финансирования',
            },
        ),
        migrations.CreateModel(
            name='NameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_ky', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Заголовок')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('descriptions_ru', models.TextField(null=True, verbose_name='Описание')),
                ('descriptions_ky', models.TextField(null=True, verbose_name='Описание')),
                ('descriptions_en', models.TextField(null=True, verbose_name='Описание')),
                ('image_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_infos', to='financing.imageform', verbose_name='Добавить Заголовок и Описание')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Информация на странице - Источники финансирования',
            },
        ),
    ]
